### PR TITLE
#1355 Allow Business Partner group without setting price system

### PR DESCRIPTION
**Pull request by metasnw**
set column ismandatory = N
https://github.com/metasfresh/metasfresh/issues/1355

### CODE REVIEW

**Review by metas-ts — COMMENTED** [review]
Hi @metasnw ,
why did you supply this SQL to metasfresh-dist as opposed to metasfresh?
isn't this a good enhancement for all metasfresh users, i.e. also dist-org users and "self-customized" users which have their own private metasfresh-dist-x ?

**Comment by metasnw** [comment]
@metas-ts I agree that it is a good thing for all dists. I just wasn't sure about the impact.

Just talked with mark and he gave me the hint that other dists that do not want that change can have a migration script undoing the change with a higher migration script number.

So its fine to put it to metasfresh main. Will you do it or shall I ?

**Comment by metas-ts** [comment]
@metasnw i'm moving it

**Comment by metas-ts** [comment]
done moving the file to metasfresh

**Pull request closed without merging**
