### PR TITLE
Changed the PROJECT_ATTR to match with the swing project.

### PR DESCRIPTION
**Pull request by walmeidasantos**
Hello there,

Trying to debug the source code using the easiest way, swing + embedded server, i got a error from eclipse that the swingui wasn't part of the project. 
I made this change and worked for me. 

I am using linux eclipse oxygen2.

This would be the first commit if am right XD

### CODE REVIEW

**Comment by teosarca** [comment]
hi @walmeidasantos,

Thanks for the PR.
Unfortunately we removed the embedded sever feature when we started to add REST and springfox/swagger, but we forgot to remove that launcher too.
I would like to delete that launcher completely and instead
* use `mf15_java.launch` launch group to start all 3 services we have
* optionally, use metasfresh-dist-swingui to start the swing ui.

**Comment by walmeidasantos** [comment]
Oh,

So next time then.

**Comment by metas-mk** [comment]
Hey @walmeidasantos,
great, thanks for your PR. Very nice to see you digging into metasfresh. Welcome to our community.

**Comment by walmeidasantos** [comment]
@metas-mk Yep! 
I am digging ! 
Soon enough i will be more productive.

**Comment by metas-ts** [comment]
closing this PR..looking forward to others :-)

**Pull request closed without merging**
